Add Kate to our team listing & Update Tracy's head shot
cityofaustin/atd-product pull request #43
Opened 2022-08-09 19:46 UTC by frankhereford

Welcome to our newest team member and thanks-in-advance for Tracy's work to help us all have great photographs!

This PR intends to close [issue 9966](https://github.com/cityofaustin/atd-data-tech/issues/9966). It includes a new photograph for Tracy and the addition of Kate to our team listing page.

2022-08-09 19:49 UTC, chiaberry approved these changes

2022-08-09 20:05 UTC, katelunceford approved these changes

2022-08-09 20:25 UTC, mateoclarke approved these changes
🚀

2022-08-10 16:15 UTC, patrickm02L requested changes
Update the titles for Janet, Annie, Jorge. Please change "Intern" to "Fellow." 

Janet Chu, Design Research Fellow
Annie Phan, Data Science Fellow
Jorge Gabitto, Software Developer Fellow

2022-08-10 16:26 UTC, merged